extends: default

rules:
  line-length:
    max: 120
    level: warning

  truthy:
    level: warning

  comments:
    require-starting-space: true

  indentation:
    indent-sequences: consistent

  trailing-spaces: enable
  new-line-at-end-of-file: enable
  document-start:
    present: false
